### ISSUE TITLE
Android Pay Button

### ISSUE THREAD

**Issue by cyerro** [android-pay/androidpay-quickstart#18] opened 2016-07-12 12:11 UTC
Hi, 

I tried running your project in android studio, I didn't see any errors but why can't I see the Buy with Android Pay button? Pleasee see attached. 
![capture](https://cloud.githubusercontent.com/assets/20377672/16766455/ce114408-486c-11e6-8579-6695737fe029.PNG)
Hope you can help me out. Thank you!

**Comment by samtstern** [comment] 2016-07-12 14:33
Do you have the Android Pay app on your device and is it loaded with a
valid credit card?

**Comment by cyerro** [comment] 2016-07-12 15:33
Hi,

Thanks for your prompt reply! I do have android pay installed in my mobile
tho my card is not accepted since my issuing bank is not a participated
bank.
Is there some test cards to be used with android pay? And is that the
reason I can't see the Buy with Android Pay button?

Thanks again!

**Comment by samtstern** [comment] 2016-07-12 16:05
Sorry right now you can't use any test cards with Android Pay.  That's the reason you can't see the button, you can see in the sample code that the button is hidden when there are no cards on the device.

Going to close this issue since the sample is working as intended.  I hope you can find a card that works!

**Closed as completed by samtstern** 2016-07-12 16:05 UTC

**Comment by cyerro** [comment] 2016-07-12 16:57
Hi,

Thank you very much for your fast answers. Last question, have you tried
integrating Android Pay via CyberSource?

Thanks a lot!

**Comment by samtstern** [comment] 2016-07-12 16:57
@cyerro nope sorry, I don't have any experience with CyberSource.

**Comment by cyerro** [comment] 2016-07-12 17:00
Hi,

No worries, thank you very much again!

Have a good night. ☺
