### ISSUE TITLE
Unable to contact with Google

### ISSUE THREAD

**Issue by cma9203** [android-pay/androidpay-quickstart#20] opened 2016-08-01 20:56 UTC
Hi, when I click "Sign in with Google" button from Login page in the emulator, it showed "An error occurring while contacting with Google. Please try again later." Can you help me about this problem?
Thanks.

**Comment by samtstern** [comment] 2016-08-09 15:44
@cma9203 I will need more information in order to debug.  First of all, are you using an emulator with Google APIs?  If so, can you go to Settings > Apps > Google Play Services and tell me what version the device is running?

**Comment by cma9203** [comment] 2016-08-09 19:03
@samtstern Hi, I think I am using  com.google.android.gms:play-services:9.4.0. 
![unnamed](https://cloud.githubusercontent.com/assets/13584219/17529734/1b28dc78-5e3a-11e6-81e5-389a8875c1ac.png)

**Comment by samtstern** [comment] 2016-08-09 19:09
Ok a few things here:
1. That is the version of your client SDK, I need to know what version the emulator is running.
2. Try not to mix versions, you're using 8.4.0 and 9.4.0 together.  Suggest moving all to 9.4.0
3. Never use the monolithic `com.google.android.gms:play-services:x.x.x` target.  Instead use the smaller, split targets like `play-services-auth` and `play-services-wallet`.  The big `play-services` target will bloat your app and introduce a number of unwanted dependencies.

**Comment by cma9203** [comment] 2016-08-09 19:30
@samtstern Sorry about that, I am kind of new to this. So I deleted the com.google.android.gms:play-services:x.x.x target.  The device I am using:

Name: Nexus_5_API_22

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\acm.android\avd\Nexus_5_API_22.avd

Target: google_apis [Google APIs](API level 22)

Skin: nexus_5

SD Card: 100M

hw.dPad: no

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5

vm.heapSize: 64

hw.device.manufacturer: Google

hw.gps: yes

image.androidVersion.api: 22

hw.audioInput: yes

image.sysdir.1: system-images\android-22\google_apis\x86\

tag.id: google_apis

hw.camera.back: none

hw.mainKeys: no

AvdId: Nexus_5_API_22

hw.camera.front: none

hw.lcd.density: 480

runtime.scalefactor: auto

avd.ini.displayname: Nexus 5 API 22

hw.gpu.mode: auto

hw.device.hash2: MD5:2fa0e16c8cceb7d385183284107c0c88

hw.ramSize: 1536

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes

**Comment by samtstern** [comment] 2016-08-09 19:37
@cma9203 no worries, happy to walk you through it.  While that's all good info, it's not quite what I need.

If you run the emulator, then on the emulator open the Settings app.  In Settings, go to Apps and then click Google Play Services.  There should be a version number displayed at this point.

**Comment by cma9203** [comment] 2016-08-09 20:05
@samtstern Thanks a lot. The version is 9.4.52.
![123](https://cloud.githubusercontent.com/assets/13584219/17531637/62a7171a-5e42-11e6-83a9-1e9de4ccf07e.PNG)
Also I found that I cannot move up the version of play-services-auth and play-services-wallet from 8.4.0 to 9.4.0, it will cause errors.

**Comment by samtstern** [comment] 2016-08-09 20:09
@cma9203 what errors do you get when going to `9.4.0`?  That could be related.

**Comment by cma9203** [comment] 2016-08-09 20:27
@samtstern The errors are:
![321](https://cloud.githubusercontent.com/assets/13584219/17532321/a59fe5b2-5e45-11e6-8552-0c30cb460cf3.PNG)
![123](https://cloud.githubusercontent.com/assets/13584219/17532323/a78c106c-5e45-11e6-9cec-8789f5964239.PNG)

**Comment by cma9203** [comment] 2016-08-09 20:30
And in the AndroidManifest.xml file, this line changed to be invalid, 
![323](https://cloud.githubusercontent.com/assets/13584219/17532446/388a588a-5e46-11e6-980c-f8a20eb5767d.PNG)
It is valid when the version is 8.4.0

**Comment by samtstern** [comment] 2016-08-09 20:53
Ok that is all good to know, let's go back to `8.4.0` and try to get the original error.  So you see that message when you hit the sign in button?  Is there anything else interesting in the logs at that time?

**Comment by cma9203** [comment] 2016-08-09 21:09
Yes. When I click the Sign in button, it will show the message.

08-09 14:56:02.963 14876-14876/com.google.android.gms.samples.wallet D/Atlas: Validating map...
08-09 14:56:03.094 14876-14906/com.google.android.gms.samples.wallet I/OpenGLRenderer: Initialized EGL, version 1.4
08-09 14:56:03.118 14876-14906/com.google.android.gms.samples.wallet D/OpenGLRenderer: Enabling debug mode 0
08-09 14:56:03.147 14876-14906/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 14:56:03.147 14876-14906/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xb4240de0, error=EGL_SUCCESS
08-09 14:58:42.531 14876-14884/com.google.android.gms.samples.wallet W/art: Suspending all threads took: 5.924ms
08-09 14:59:14.327 17409-17409/com.google.android.gms.samples.wallet I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
08-09 14:59:56.769 17409-17409/com.google.android.gms.samples.wallet W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
08-09 14:59:56.769 17409-17409/com.google.android.gms.samples.wallet W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
08-09 14:59:56.818 17409-17409/com.google.android.gms.samples.wallet W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
08-09 14:59:56.818 17409-17409/com.google.android.gms.samples.wallet W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
08-09 14:59:56.820 17409-17409/com.google.android.gms.samples.wallet D/ChimeraCfgMgr: Reading stored module config
08-09 14:59:56.843 17409-17409/com.google.android.gms.samples.wallet D/ChimeraFileApk: Primary ABI of requesting process is x86
08-09 14:59:56.844 17409-17409/com.google.android.gms.samples.wallet D/ChimeraFileApk: Classloading successful. Optimized code found.
08-09 14:59:56.939 17409-17428/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 14:59:56.939 17409-17428/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa3481820, error=EGL_SUCCESS
08-09 15:00:07.686 17409-17428/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 15:00:07.686 17409-17428/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa34dd920, error=EGL_SUCCESS
08-09 15:00:07.857 17409-17409/com.google.android.gms.samples.wallet W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
08-09 15:00:08.475 17409-17409/com.google.android.gms.samples.wallet D/GoogleSignInApiImpl: getSavedSignInResultIfEligible
08-09 15:00:08.475 17409-17409/com.google.android.gms.samples.wallet D/GoogleSignInApiImpl: trySilentSignIn
08-09 15:00:08.749 17409-17428/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 15:00:08.749 17409-17428/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa3481660, error=EGL_SUCCESS
08-09 15:00:08.821 17409-17428/com.google.android.gms.samples.wallet V/RenderScript: 0xae949000 Launching thread(s), CPUs 2
08-09 15:00:19.851 17409-17428/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 15:00:19.851 17409-17428/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa34dde60, error=EGL_SUCCESS
08-09 15:00:19.947 17409-17409/com.google.android.gms.samples.wallet W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
08-09 15:00:20.304 17409-17409/com.google.android.gms.samples.wallet D/GoogleSignInApiImpl: getSavedSignInResultIfEligible
08-09 15:00:20.304 17409-17409/com.google.android.gms.samples.wallet D/GoogleSignInApiImpl: trySilentSignIn
08-09 15:00:20.394 17409-17428/com.google.android.gms.samples.wallet W/EGL_emulation: eglSurfaceAttrib not implemented
08-09 15:00:20.394 17409-17428/com.google.android.gms.samples.wallet W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xb437ab00, error=EGL_SUCCESS

This are all logs I got, I searched some of them warnings or failures, I think they are not related to the real reason for that error.

**Comment by samtstern** [comment] 2016-08-09 21:57
Ok that error comes from here:
https://github.com/android-pay/androidpay-quickstart/blob/3e6806cecc7cc864bc433de0768a1a7c392ba6f1/app/src/main/java/com/google/android/gms/samples/wallet/LoginFragment.java#L152

I will take a look soon, thanks so much for the back-and-forth!

**Comment by samtstern** [comment] 2016-08-10 16:27
@cma9203 I've gone through this myself and the only way I could reproduce that error was to have an incorrectly configured client ID (wrong package or SHA1).

Please make sure you have followed all the steps here: https://developers.google.com/android-pay/android/tutorial#obtain_credentials_and_a_client_id_for_your_app

Also I have updated the sample to produce more logs in this situation, so if you pull the latest source that could help you troubleshoot.

**Comment by cma9203** [comment] 2016-08-10 18:42
@samtstern Sounds great. That might be the problem. I will try it out. Thanks a lot.

**Comment by samtstern** [comment] 2017-10-24 18:41
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.

**Closed as completed by samtstern** 2017-10-24 18:41 UTC
